name: Export CF Pack

on:
  push:
    branches: '1.7.10'
  workflow_dispatch:

jobs:
  Export-Modpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: false

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Export CF Pack
        run: |
          packwiz curseforge export
          mv ./*.zip "Sky SC Client 1.7.10 v1.0.zip"
      
      - name: Upload Sky SC Client
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Sky SC Client 1.7.10"
          automatic_release_tag: "1.7.10_latest"
          repo_token: "${{ secrets.UPLOAD_RELEASES }}"
          files: "./*.zip"
          prerelease: false
      